// src/components/projects/website.tsx
import { useEffect, useState } from "react";
import type { ProjectType } from "@/data/projects";

const Website = ({
   tab, data, hidden,
}: {
   tab: number, data: ProjectType[], hidden: boolean,
}) => {
   const [loaded, setLoaded] = useState(
      Array.from({ length: data.length }, (_, index) => index === 0)
   );

   useEffect(() => {
      if (!loaded[tab]) {
         setLoaded((prevLoaded) => {
            const newLoaded = [...prevLoaded];
            newLoaded[tab] = true;
            return newLoaded;
         });
      }
   }, [tab, loaded])

   return (
      <div
         className="w-full h-full center relative"
         style={{ display: hidden ? "none" : "block" }}
      >
         {data.map((project, index) => (
            loaded[index] && (
               <iframe
                  key={index}
                  className="w-full h-full max-md:rounded-2xl"
                  hidden={tab !== index}
                  aria-hidden={tab !== index}
                  src={project.website}
                  title={`Project showcase: ${project.title}`}
               />
            )
         ))}
      </div>
   );
};

export default Website;

// nuxt/app/components/projects/website.vue
<script setup lang="ts">
import { projects } from "~/content/projects";
import type { ScreenStoreType } from "~~/types/store";

const store = inject("store") as ScreenStoreType;

const webWrapperRef = useTemplateRef("webWrapperRef");
const { width, height } = useElementSize(webWrapperRef);
</script>

<template>
  <div
    ref="webWrapperRef"
    class="wh-full relative hidden"
    :style="{ display: store.state.previewApp === 2 ? 'block' : 'none' }"
  >
    <div
      v-for="({ website, name, webBgImg }, index) in projects"
      :key="index"
      :class="{
        'wh-full relative hidden': true,
        'bg-[#2a2a2a]': index === 0,
        'bg-[#a67a42]': index === 1,
      }"
      :style="{
        width: `${width}px`,
        height: `${height}px`,
        display: store.state.previewProject === index ? 'block' : 'none',
      }"
    >
      <div class="sr-only">
        <h2>{{ name }}</h2>
        <p>
          This is a live preview of project: <strong>{{ name }}</strong
          >.
        </p>
        <UiExternalLink :href="website">Visit {{ website }}</UiExternalLink>
      </div>
      <div class="wh-full">
        <img
          :src="webBgImg"
          class="wh-full blur-sm absolute z-10 top-0"
          role="presentation"
          aria-hidden="true"
        />
        <iframe
          class="wh-full max-md:rounded-2xl absolute z-20 top-0"
          :src="website"
          :title="`Project showcase: ${name}`"
        />
      </div>
    </div>
  </div>
</template>
