// nuxt/components/projects/screen.vue
<script setup lang="ts">
import { projects } from "~/data/projects";
import type { ProjectDataType } from "~/types/github";

import type {
  ScreenStoreActionType,
  ScreenStoreStateType,
  ScreenStoreType,
} from "~/types/store";

const state = reactive<ScreenStoreStateType>({
  previewProject: 1,
  previewApp: 3,
  data: [],
});

const isDataAvailable = computed<boolean>(() => state.data.length !== 0);

const dispatch = ({ type, payload }: ScreenStoreActionType) => {
  switch (type) {
    case "TOGGLE_PROJECT": {
      state.previewProject = payload;
      break;
    }
    case "TOGGLE_APP": {
      state.previewApp = payload;
      break;
    }
    default: {
      throw new Error("Unknown action");
    }
  }
};

const store: ScreenStoreType = { state, dispatch };
provide("store", store);

// For development purpose
// import response from "~/data/dev/tmp-fetch-all-response";
// store.state.data = response;

onMounted(async () => {
  const fetchPromises = projects.map((project) => {
    const baseUrl = `https://api.github.com/repos/${project.repo}`;
    return Promise.all([
      fetch(baseUrl).then((res) => res.json()), // repoDetails
      fetch(`${baseUrl}/languages`).then((res) => res.json()), // languages
      fetch(`${baseUrl}/contributors`).then((res) => res.json()), // contributors
      fetch(`${baseUrl}/branches`).then((res) => res.json()), // branches
      fetch(`${baseUrl}/tags`).then((res) => res.json()), // tags
      fetch(`${baseUrl}/contents/LICENSE`) // license
        .then(async (res) => {
          const data = await res.json();
          return data.message === "Not Found" ? null : data;
        }),
      fetch(`${baseUrl}/contents/README.md`) // readme
        .then(async (res) => {
          const data = await res.json();
          return data.message === "Not Found" ? null : data;
        }),
    ]);
  });

  try {
    const results = await Promise.all(fetchPromises);
    const formattedData: ProjectDataType[] = results.map(
      ([
        repoDetails,
        languages,
        contributors,
        branches,
        tags,
        license,
        readme,
      ]) => ({
        repoDetails,
        languages,
        contributors,
        branches,
        tags,
        license,
        readme,
      })
    );
    
    store.state.data = formattedData;
  } catch (error) {
    console.error("Error fetching data from GitHub API:", error);
  }
});

const isWebsiteComponentHidden = computed(() => store.state.previewApp !== 3);
const isGithubComponentVisible = computed(() => store.state.previewApp === 5);
const previewData = computed<ProjectDataType>(
  () => store.state.data[store.state.previewProject - 1]
);
</script>

<template>
  <ProjectsFloatingDock />
  <div class="h-full w-full overflow-auto scroll">
    <ProjectsWebsite :hidden="isWebsiteComponentHidden" />
    <ProjectsAbout
      :preview-project="store.state.previewProject"
      :preview-app="store.state.previewApp"
    />
    <div v-show="isGithubComponentVisible" class="bg-[#0d1117] h-full">
      <ProjectsGithub v-if="isDataAvailable" :data="previewData" />
      <ProjectsScreenFallbackGithubUi
        v-else
        :repo="projects[store.state.previewProject]?.repo"
      />
    </div>
  </div>
</template>

<style>
.scroll {
  overflow: auto;
  scrollbar-width: thin;
  scrollbar-color: #5b5d61 #191919;
}

.scroll::-webkit-scrollbar {
  width: 8px;
}
</style>

// src/components/projects/screen.tsx
import {
  useContext,
  useState,
  useEffect,
  createContext,
} from "react";

import { projects } from "@/data/projects";
import About from "./about";
import Github from "./github";
import Website from "./website";
import { FloatingDock } from "../ui/floating-dock";

import type {
  RepoDataType,
  GithubBranchesType,
  GitHubContributorType,
  GitHubFileContentType,
  GitHubLanguagesType,
  GitHubRepositoryType,
  GithubTagsType,
  ScreenContextType
} from "@/types/projects";

const ScreenContext = createContext<ScreenContextType | null>(null);

const useScreen = () => {
  const context = useContext(ScreenContext);
  if (context === null) {
    throw new Error('useScreen must be used within a ScreenProvider');
  }
  return context;
};

const Screen = () => {
  const [previewProject, setPreviewProject] = useState<number>(1); // 1 - 2
  const [previewApp, setPreviewApp] = useState<number>(3); // 3 - 5
  const [data, setData] = useState<RepoDataType[]>([]);
  const isDataAvilable: boolean = data.length !== 0;
  const previewProjectIndex = previewProject - 1;

  const setScreen = (value: number, view: "project" | "app") => {
    const handlers = {
      project: setPreviewProject,
      app: setPreviewApp,
    };

    handlers[view](value);
  };

  useEffect(() => {
    (async () => {
      const fetchPromises = projects.map(project => {
        const baseUrl = `https://api.github.com/repos/${project.repo}`;
        return Promise.all([
          fetch(baseUrl).then(res => res.json() as Promise<GitHubRepositoryType>),
          fetch(`${baseUrl}/languages`).then(res => res.json() as Promise<GitHubLanguagesType>),
          fetch(`${baseUrl}/contributors`).then(res => res.json() as Promise<GitHubContributorType>),
          fetch(`${baseUrl}/branches`).then(res => res.json() as Promise<GithubBranchesType>),
          fetch(`${baseUrl}/tags`).then(res => res.json() as Promise<GithubTagsType>),
          fetch(`${baseUrl}/contents/LICENSE`)
            .then(async res => {
              const data = await res.json();
              return data.message === "Not Found" ? null : (data as GitHubFileContentType);
            }), // License
          fetch(`${baseUrl}/contents/README.md`)
            .then(async res => {
              const data = await res.json();
              return data.message === "Not Found" ? null : (data as GitHubFileContentType);
            }) // README
        ]);
      });

      try {
        const results = await Promise.all(fetchPromises);
        const formattedData = results.map(([
          repoDetails,
          languages,
          contributors,
          branches,
          tags,
          license,
          readme
        ]) => ({
          repoDetails,
          languages,
          contributors,
          branches,
          tags,
          license,
          readme,
        }));
        setData(formattedData);

      } catch (error) {
        console.error('Error fetching data from GitHub API:', error);
      }
    })();
  }, []);

  return (
    <>
      <ScreenContext.Provider value={{ previewProject, previewApp, setScreen }}>
        <FloatingDock />
      </ScreenContext.Provider>
      <div className="overflow-scroll h-full w-full">
        <Website
          tab={previewProjectIndex}
          data={projects}
          hidden={previewApp !== 3}
        />
        <About number={[previewProject, previewApp]} />
        {isDataAvilable && (
          <Github
            data={data[previewProjectIndex]}
            hidden={previewApp !== 5}
          />
        )}
      </div>
    </>
  )
};

export { Screen as default, ScreenContext, useScreen };
