// nuxt/app/components/flip-words.vue
<script setup lang="ts">
// Inspiration URL: https://ui.aceternity.com/components/flip-words
// Source URL: https://inspira-ui.com/components/text-animations/flip-words

const {
  words,
  duration = 3000,
  className = "",
} = defineProps<{
  words: string[];
  duration?: number;
  className?: string;
}>();

defineEmits(["animationStart", "animationComplete"]);

const currentWord = ref(words[0]);
const isVisible = ref(true);
const timeoutId = ref<number | null>(null);

const startAnimation = (): void => {
  isVisible.value = false;

  setTimeout(() => {
    const currentIndex = words.indexOf(currentWord.value);
    const nextWord = words[currentIndex + 1] || words[0];
    currentWord.value = nextWord;
    isVisible.value = true;
  }, 600);
};

const splitWords = computed(() => {
  return currentWord.value.split(" ").map((word) => ({
    word,
    letters: word.split(""),
  }));
});

const startTimeout = (): void => {
  timeoutId.value = window.setTimeout(() => {
    startAnimation();
  }, duration);
};

onMounted(() => {
  startTimeout();
});

onBeforeUnmount(() => {
  if (timeoutId.value) {
    clearTimeout(timeoutId.value);
  }
});

watch(isVisible, (newValue) => {
  if (newValue) {
    startTimeout();
  }
});
</script>

<template>
  <div class="relative inline-block px-2 text-current">
    <Transition
      enter-active-class="word-enter-active"
      leave-active-class="word-leave-active"
      @after-enter="$emit('animationStart')"
      @after-leave="$emit('animationComplete')"
    >
      <div
        v-show="isVisible"
        :class="
          useCn(
            'relative z-10 inline-block text-left text-neutral-600',
            className
          )
        "
      >
        <template
          v-for="(wordObj, wordIndex) in splitWords"
          :key="wordObj.word + wordIndex"
        >
          <span
            class="word-fade-in"
            :style="{ animationDelay: `${wordIndex * 0.3}s` }"
          >
            <span
              v-for="(letter, letterIndex) in wordObj.letters"
              :key="wordObj.word + letterIndex"
              class="letter-fade-in"
              :style="{
                animationDelay: `${wordIndex * 0.3 + letterIndex * 0.05}s`,
              }"
            >
              {{ letter }}
            </span>
            <span class="inline-block">&nbsp;</span>
          </span>
        </template>
      </div>
    </Transition>
  </div>
</template>

<style>
.word-fade-in {
  @apply inline-block whitespace-nowrap opacity-0;
  animation: wordFadeIn 0.3s ease forwards;
}

.letter-fade-in {
  @apply inline-block opacity-0;
  animation: letterFadeIn 0.2s ease forwards;
}

.word-enter-active {
  animation: wordEnter 0.6s ease-in-out forwards;
}

.word-leave-active {
  animation: wordLeave 0.6s ease-in-out forwards;
}

@keyframes wordFadeIn {
  0% {
    opacity: 0;
    transform: translateY(10px);
    filter: blur(8px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
    filter: blur(0);
  }
}

@keyframes letterFadeIn {
  0% {
    opacity: 0;
    transform: translateY(10px);
    filter: blur(8px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
    filter: blur(0);
  }
}

@keyframes wordEnter {
  0% {
    opacity: 0;
    transform: translateY(10px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes wordLeave {
  0% {
    opacity: 1;
    transform: scale(1);
    filter: blur(0);
  }
  100% {
    opacity: 0;
    transform: scale(2);
    filter: blur(8px);
  }
}
</style>

// src/components/ui/flip-words.tsx
"use client";
import React, { useCallback, useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

export const FlipWords = ({
   words,
   duration = 3000,
}: {
   words: string[];
   duration?: number;
}) => {
   const [currentWord, setCurrentWord] = useState(words[0]);
   const [isAnimating, setIsAnimating] = useState<boolean>(false);

   const startAnimation = useCallback(() => {
      const word = words[words.indexOf(currentWord) + 1] || words[0];
      setCurrentWord(word);
      setIsAnimating(true);
   }, [currentWord, words]);

   useEffect(() => {
      if (!isAnimating)
         setTimeout(() => {
            startAnimation();
         }, duration);
   }, [isAnimating, duration, startAnimation]);

   return (
      <AnimatePresence
         onExitComplete={() => {
            setIsAnimating(false);
         }}
      >
         <motion.div
            initial={{
               opacity: 0,
               y: 10,
            }}
            animate={{
               opacity: 1,
               y: 0,
            }}
            transition={{
               type: "spring",
               stiffness: 100,
               damping: 10,
            }}
            exit={{
               opacity: 0,
               y: -40,
               x: 40,
               filter: "blur(8px)",
               scale: 2,
               position: "absolute",
            }}
            className="z-10 inline-block relative text-left text-neutral-900 px-2"
            key={currentWord}
         >
            {currentWord.split(" ").map((word, wordIndex) => (
               <motion.span
                  key={word + wordIndex}
                  initial={{ opacity: 0, y: 10, filter: "blur(8px)" }}
                  animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  transition={{
                     delay: wordIndex * 0.3,
                     duration: 0.3,
                  }}
                  className="inline-block whitespace-nowrap"
               >
                  {word.split("").map((letter, letterIndex) => (
                     <motion.span
                        key={word + letterIndex}
                        initial={{ opacity: 0, y: 10, filter: "blur(8px)" }}
                        animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                        transition={{
                           delay: wordIndex * 0.3 + letterIndex * 0.05,
                           duration: 0.2,
                        }}
                        className="inline-block"
                     >
                        {letter}
                     </motion.span>
                  ))}
                  <span className="inline-block">&nbsp;</span>
               </motion.span>
            ))}
         </motion.div>
      </AnimatePresence >
   );
};
