// nuxt/components/ui/label.vue
<script setup lang="ts">
defineProps({
  /**
   * Additional CSS classes to apply to the label.
   */
  className: {
    type: String,
    default: '',
  },
});
</script>

<template>
  <label :class="cn('text-sm md:text-base font-medium text-black leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-left px-2'
    , className)">
    <slot />
  </label>
</template>

// src/components/ui/label.tsx
import type { LabelHTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/utils";

const Label = ({
  children,
  className,
  ...rest
}: {
  children: string | ReactNode,
  className?: string,
} & LabelHTMLAttributes<HTMLLabelElement>) => (
  <label
    className={cn(
      "text-sm md:text-base font-medium text-black leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 text-left px-2",
      className,
    )}
    {...rest}
  >
    {children}
  </label>
);

export default Label;
