// nuxt/app/components/tools-pack.vue
<script setup lang="ts">
import { hierarchy, pack, type HierarchyCircularNode } from "d3-hierarchy";
import tools, { type ToolsType } from "~/data/tools";

// Inspiration URL: https://tanstack.com/query/latest
// Source URL: https://github.com/TanStack/tanstack.com/blob/ee943e214df6f132a70120014096ed72775dee4b/app/components/ToolsPack.tsx

export type CircleData = {
  x: number;
  y: number;
  r: number;
  data: ToolsType;
};

const { isTouch } = useCustomPointer();
const isMounted = useMounted();
const container = useTemplateRef("container");
const { width } = useElementSize(container, { width: 200, height: 0 });

const computeD3Layout = (tools: ToolsType[], size: number): CircleData[] => {
  const rootNode = hierarchy<{ children: ToolsType[]; name: string }>({
    children: tools,
    name: "root",
  })
    .sum((d: any) => d.proficiency || 1)
    .sort(
      (a: any, b: any) => (b.data.proficiency || 0) - (a.data.proficiency || 0)
    );

  const root = pack()
    .size([size, size])
    .padding(size * 0.005)(rootNode as HierarchyCircularNode<unknown>);

  return root
    .descendants()
    .slice(1)
    .map(
      (node): CircleData => ({
        x: node.x,
        y: node.y,
        r: node.r,
        data: node.data as ToolsType,
      })
    );
};

const circles = ref(computeD3Layout(tools, width.value));
const recalculate = () => {
  circles.value = computeD3Layout(tools, width.value);
};

const getTooltipClasses = (x: number, y: number): string[] => {
  const tooltipX = x > width.value / 2 ? "left" : "right";
  const tooltipY = y > width.value / 2 ? "top" : "bottom";

  return [
    tooltipX === "left"
      ? "left-1/4 -translate-x-full"
      : "right-1/4 translate-x-full",
    tooltipY === "top"
      ? "top-1/4 -translate-y-full"
      : "bottom-1/4 translate-y-full",
  ];
};

watch(width, recalculate);
</script>

<template>
  <div
    ref="container"
    :class="{
      'max-w-[1000px] aspect-square lg:mx-auto max-xl:mx-10 max-md:mx-8 max-xs:mx-5': true,
      'py-[400px]': !isMounted,
    }"
  >
    <p class="sr-only" aria-hidden="false">
      My core development stack includes <b>Nuxt.js</b> for full-stack
      applications, <b>React</b> and <b>Vue.js</b> for frontend frameworks,
      <b>TypeScript</b> for type-safe JavaScript, <b>Figma</b> for design
      collaboration, and <b>Tailwind CSS</b> for utility-first styling. I
      frequently deploy with <b>Vercel</b> and also work with
      <b>React Native</b> for mobile app development.
    </p>

    <div
      @mousemove="useBlurAll"
      :class="[
        'h-full relative mx-auto',
        isMounted ? 'w-full' : 'w-[200px]',
        isMounted ? 'h-full' : 'h-[200px]',
      ]"
    >
      <div
        v-for="(circle, i) in circles"
        :key="`circle-${i}`"
        class="circle-item"
        :style="{
          left: `${circle.x - circle.r}px`,
          top: `${circle.y - circle.r}px`,
          width: `${circle.r * 2}px`,
          height: `${circle.r * 2}px`,
        }"
      >
        <div
          class="circle-image"
          role="img"
          :aria-label="`${circle.data.name} logo`"
          tabindex="-1"
          v-html="
            circle.data.imageUrl.startsWith('<svg')
              ? circle.data.imageUrl
              : undefined
          "
          :style="
            !circle.data.imageUrl.startsWith('<svg')
              ? { backgroundImage: `url(${circle.data.imageUrl})` }
              : undefined
          "
        />
        <div
          :class="[
            'circle-tooltip',
            getTooltipClasses(circle.x, circle.y),
            isTouch ? 'underline' : 'hover:underline',
          ]"
        >
          <UiExternalLink :href="circle.data.linkUrl" class="circle-tooltip-a">
            {{ circle.data.name }}
          </UiExternalLink>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/ui/tools-pack.tsx
import { useMemo } from 'react';
import { Pack, hierarchy } from '@visx/hierarchy';
import { ParentSize } from '@visx/responsive';

import type { HierarchyNode } from '@visx/hierarchy/lib/types';
import type { ToolsType } from "@/types/tools";

import { cn } from '@/lib/utils';

// Inspiration URL: https://tanstack.com/query/latest
// Source URL: https://github.com/TanStack/tanstack.com/blob/ee943e214df6f132a70120014096ed72775dee4b/app/components/ToolsPack.tsx   

const ToolsPack = ({ tools }: { tools: ToolsType[] }) => {
   const pack = useMemo<ToolsType>(
      () => ({
         children: tools,
         name: 'root',
         radius: 0,
         distance: 0,
      }),
      [tools]
   );

   const root = useMemo(() =>
      hierarchy<ToolsType>(pack)
         .sum((d) => d.proficiency || 1)
         .sort((a, b) => (b.data.proficiency ?? 0) - (a.data.proficiency ?? 0)),
      [pack]
   );

   return (
      <ParentSize>
         {({ width = 800 }) => width < 10 ? null : (
            <div style={{ width, height: width, position: 'relative' }}>
               <Pack root={root} size={[width, width]} padding={width * 0.005}>
                  {(packData: HierarchyNode<ToolsType>) => {
                     const circles = packData.descendants().slice(1) as Array<HierarchyNode<ToolsType> & { x: number; y: number; r: number }>;
                     return (
                        <div>
                           {[...circles].reverse().map(({ x, y, r, data }, i) => {
                              const tooltipX = x > width / 2 ? 'left' : 'right';
                              const tooltipY = y > width / 2 ? 'top' : 'bottom';

                              return (
                                 <div
                                    key={`circle-${i}`}
                                    // href={circle.data.linkUrl}
                                    className="spon-link absolute shadow-lg bg-white rounded-full z-0 border-[0.5px]"
                                    style={{ left: x, top: y, width: r * 2, height: r * 2 }}
                                 >
                                    {typeof data.imageUrl === "string" ? (
                                       <div
                                          key={`circle-${i}`}
                                          className="absolute bg-no-repeat bg-center bg-contain rounded-full w-[95%] h-[95%] left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
                                          style={{ backgroundImage: `url(${data.imageUrl})` }}
                                       />
                                    ) : data.imageUrl}
                                    <div
                                       className={cn(
                                          "spon-tooltip absolute z-50 text-sm bg-gray-800 text-white p-2 pointer-events-none transform opacity-0 shadow-xl rounded-lg flex flex-col items-center",
                                          tooltipX == 'left' ? 'left-1/4 -translate-x-full' : 'right-1/4 translate-x-full',
                                          tooltipY == 'top' ? 'top-1/4 -translate-y-full' : 'bottom-1/4 translate-y-full',
                                       )}
                                    >
                                       <p className={`whitespace-nowrap font-bold z-20 relative`}>
                                          {data.name}
                                       </p>
                                    </div>
                                 </div>
                              )
                           })}
                        </div>
                     );
                  }}
               </Pack>
            </div>
         )}
      </ParentSize>
   );
}

export default ToolsPack;
